export const spellTables = {
  ////prepared spells is spellmod + level //

  //Make each class their own separate table: more lines of code, but simplicity in logic and much more easy to find/edit
  //Full Casters
  //bard(gets spellsKnown thru separate table)
  //Cleric  (need to make cantrip table)
  //Druid: diff cantrip table
  //Sorc: diff cantrip and spellsKnown table
  //Wizard: diff cantrip table

  //spells known are same as prepared spells for bards
  bard: {
    1: { spellsKnown: 4, cantrips: 2, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { spellsKnown: 5, cantrips: 2, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { spellsKnown: 6, cantrips: 2, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { spellsKnown: 7, cantrips: 3, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { spellsKnown: 8, cantrips: 3, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { spellsKnown: 9, cantrips: 3, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { spellsKnown: 10, cantrips: 3, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { spellsKnown: 11, cantrips: 3, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { spellsKnown: 12, cantrips: 3, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { spellsKnown: 14, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { spellsKnown: 15, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    12: { spellsKnown: 15, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    13: { spellsKnown: 16, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    14: { spellsKnown: 18, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    15: { spellsKnown: 19, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    16: { spellsKnown: 19, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    17: { spellsKnown: 20, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    18: { spellsKnown: 22, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    19: { spellsKnown: 22, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 1, eighth: 1, ninth: 1 },
    20: { spellsKnown: 22, cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 2, eighth: 1, ninth: 1 },
  },

  cleric: {
    1: { cantrips: 3, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 3, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 3, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 4, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 4, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    14: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    15: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    16: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    17: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    18: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    19: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 1, eighth: 1, ninth: 1 },
    20: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 2, eighth: 1, ninth: 1 },
  },

  druid: {
    1: { cantrips: 2, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 2, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 2, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 3, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 3, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 3, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 3, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 3, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 3, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    14: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    15: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    16: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    17: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    18: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    19: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 1, eighth: 1, ninth: 1 },
    20: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 2, eighth: 1, ninth: 1 },
  },
  //prepared spells is spellmod + half level rounded down: Half-casters
  //Paladin--have access to all paladin spells, need to prepare every morning
  //Ranger
  paladin: {
    1: { cantrips: 0, first: 0, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 0, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 0, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 0, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 0, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 0, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 0, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 0, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 0, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 0, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    14: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    15: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    16: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    17: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    18: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    19: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    20: { cantrips: 0, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
  },

  ranger: {
    1: { cantrips: 0, spellsKnown: 0, first: 0, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 0, spellsKnown: 2, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 0, spellsKnown: 3, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 0, spellsKnown: 3, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 0, spellsKnown: 4, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 0, spellsKnown: 4, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 0, spellsKnown: 5, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 0, spellsKnown: 5, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 0, spellsKnown: 6, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 0, spellsKnown: 6, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 0, spellsKnown: 7, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 0, spellsKnown: 7, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 0, spellsKnown: 8, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    14: { cantrips: 0, spellsKnown: 8, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    15: { cantrips: 0, spellsKnown: 9, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    16: { cantrips: 0, spellsKnown: 9, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    17: { cantrips: 0, spellsKnown: 10, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    18: { cantrips: 0, spellsKnown: 10, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    19: { cantrips: 0, spellsKnown: 11, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    20: { cantrips: 0, spellsKnown: 11, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
  },

  sorceror: {
    1: { cantrips: 4, spellsKnown: 2, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 4, spellsKnown: 3, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 4, spellsKnown: 4, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 5, spellsKnown: 5, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 5, spellsKnown: 6, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 5, spellsKnown: 7, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 5, spellsKnown: 8, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 5, spellsKnown: 9, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 5, spellsKnown: 10, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 6, spellsKnown: 11, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 6, spellsKnown: 12, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 6, spellsKnown: 12, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 6, spellsKnown: 13, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    14: { cantrips: 6, spellsKnown: 13, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    15: { cantrips: 6, spellsKnown: 14, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    16: { cantrips: 6, spellsKnown: 14, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    17: { cantrips: 6, spellsKnown: 15, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    18: { cantrips: 6, spellsKnown: 15, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    19: { cantrips: 6, spellsKnown: 15, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 1, eighth: 1, ninth: 1 },
    20: { cantrips: 6, spellsKnown: 15, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 2, eighth: 1, ninth: 1 },
  },

  //for the purposeses of simplifying rendering logic, I've given the warlock the same framework as the other casters
  warlock: {
    1: { cantrips: 2, spellsKnown: 2, spellSlots: 1, slotLevel: "first", mysticArcanum: 0, first: 1, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 2, spellsKnown: 3, spellSlots: 2, slotLevel: "first", mysticArcanum: 0, first: 1, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 2, spellsKnown: 4, spellSlots: 2, slotLevel: "second", mysticArcanum: 0, first: 1, second: 1, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 3, spellsKnown: 5, spellSlots: 2, slotLevel: "second", mysticArcanum: 0, first: 1, second: 1, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 3, spellsKnown: 6, spellSlots: 2, slotLevel: "third", mysticArcanum: 0, first: 1, second: 1, third: 1, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 3, spellsKnown: 7, spellSlots: 2, slotLevel: "third", mysticArcanum: 0, first: 1, second: 1, third: 1, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 3, spellsKnown: 8, spellSlots: 2, slotLevel: "fourth", mysticArcanum: 0, first: 1, second: 1, third: 1, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 3, spellsKnown: 9, spellSlots: 2, slotLevel: "fourth", mysticArcanum: 0, first: 1, second: 1, third: 1, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 3, spellsKnown: 10, spellSlots: 2, slotLevel: "fifth", mysticArcanum: 0, first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 4, spellsKnown: 10, spellSlots: 2, slotLevel: "fifth", mysticArcanum: 0, first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 4, spellsKnown: 11, spellSlots: 3, slotLevel: "fifth", mysticArcanum: "sixth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 4, spellsKnown: 11, spellSlots: 3, slotLevel: "fifth", mysticArcanum: "sixth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 4, spellsKnown: 12, spellSlots: 3, slotLevel: "fifth", mysticArcanum: "seventh", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    14: { cantrips: 4, spellsKnown: 12, spellSlots: 3, slotLevel: "fifth", mysticArcanum: "seventh", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    15: { cantrips: 4, spellsKnown: 13, spellSlots: 3, slotLevel: "fifth", mysticArcanum: "eigth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    16: { cantrips: 4, spellsKnown: 13, spellSlots: 3, slotLevel: "fifth", mysticArcanum: "eigth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    17: { cantrips: 4, spellsKnown: 14, spellSlots: 4, slotLevel: "fifth", mysticArcanum: "ninth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    18: { cantrips: 4, spellsKnown: 14, spellSlots: 4, slotLevel: "fifth", mysticArcanum: "ninth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    19: { cantrips: 4, spellsKnown: 15, spellSlots: 4, slotLevel: "fifth", mysticArcanum: "ninth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    20: { cantrips: 4, spellsKnown: 15, spellSlots: 4, slotLevel: "fifth", mysticArcanum: "ninth", first: 1, second: 1, third: 1, fourth: 1, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
  },

  //wizards have spellbooks to track all of their known spells
  wizard: {
    1: { cantrips: 3, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 3, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 3, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 4, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 4, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    14: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    15: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    16: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    17: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    18: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    19: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 1, eighth: 1, ninth: 1 },
    20: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 2, eighth: 1, ninth: 1 },
  },

  //Will need to add artificer cantrips, and maybe infusions tracker as well)
};

export default spellTables;
