export const spellTables = (props) => {
  const fullCaster = {
    1: { cantrips: 3, first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { cantrips: 3, first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { cantrips: 3, first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { cantrips: 4, first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { cantrips: 4, first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { cantrips: 4, first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    12: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 0, eighth: 0, ninth: 0 },
    13: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    14: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 0, ninth: 0 },
    15: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    16: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 0 },
    17: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    18: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 1, seventh: 1, eighth: 1, ninth: 1 },
    19: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 1, eighth: 1, ninth: 1 },
    20: { cantrips: 5, first: 4, second: 3, third: 3, fourth: 3, fifth: 3, sixth: 2, seventh: 2, eighth: 1, ninth: 1 },
  };

  const halfCaster = {
    1: { first: 0, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    2: { first: 2, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    3: { first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    4: { first: 3, second: 0, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    5: { first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    6: { first: 4, second: 2, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    7: { first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    8: { first: 4, second: 3, third: 0, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    9: { first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    10: { first: 4, second: 3, third: 2, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    11: { first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    12: { first: 4, second: 3, third: 3, fourth: 0, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    13: { first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    14: { first: 4, second: 3, third: 3, fourth: 1, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    15: { first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    16: { first: 4, second: 3, third: 3, fourth: 2, fifth: 0, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    17: { first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    18: { first: 4, second: 3, third: 3, fourth: 3, fifth: 1, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    19: { first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
    20: { first: 4, second: 3, third: 3, fourth: 3, fifth: 2, sixth: 0, seventh: 0, eighth: 0, ninth: 0 },
  };

  const warlock = {
    1: { cantrips: 2, spellsKnown: 2, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    2: { cantrips: 2, spellsKnown: 3, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    3: { cantrips: 2, spellsKnown: 4, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    4: { cantrips: 3, spellsKnown: 5, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    5: { cantrips: 3, spellsKnown: 6, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    6: { cantrips: 3, spellsKnown: 7, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    7: { cantrips: 3, spellsKnown: 8, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    8: { cantrips: 3, spellsKnown: 9, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    9: { cantrips: 3, spellsKnown: 10, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    10: { cantrips: 4, spellsKnown: 10, spellSlots: 4, slotLevel: 5, mysticArcanum: 0 },
    11: { cantrips: 4, spellsKnown: 11, spellSlots: 4, slotLevel: 5, mysticArcanum: 6 },
    12: { cantrips: 4, spellsKnown: 11, spellSlots: 4, slotLevel: 5, mysticArcanum: 6 },
    13: { cantrips: 4, spellsKnown: 12, spellSlots: 4, slotLevel: 5, mysticArcanum: 7 },
    14: { cantrips: 4, spellsKnown: 12, spellSlots: 4, slotLevel: 5, mysticArcanum: 7 },
    15: { cantrips: 4, spellsKnown: 13, spellSlots: 4, slotLevel: 5, mysticArcanum: 8 },
    16: { cantrips: 4, spellsKnown: 13, spellSlots: 4, slotLevel: 5, mysticArcanum: 8 },
    17: { cantrips: 4, spellsKnown: 14, spellSlots: 4, slotLevel: 5, mysticArcanum: 9 },
    18: { cantrips: 4, spellsKnown: 14, spellSlots: 4, slotLevel: 5, mysticArcanum: 9 },
    19: { cantrips: 4, spellsKnown: 15, spellSlots: 4, slotLevel: 5, mysticArcanum: 9 },
    20: { cantrips: 4, spellsKnown: 15, spellSlots: 4, slotLevel: 5, mysticArcanum: 9 },
  };
};

export default spellTables;
